services:
  whatsbot:
    build: .
    container_name: adabot
    restart: always
    init: true
    shm_size: '2gb'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHROME_PATH=/usr/bin/google-chrome-stable
    env_file:
      - ./.env