export const botResponses: string[] = [
    'Opa! Você me chamou? ✨ Se precisar de algo, é só mandar um /start que eu te ajudo com todo carinho!',
    'Tcharaaam~! 🌟 Cheguei igual surpresa boa! Que tal testar o /sticker e criar figurinhas super fofas? 💖',
    'AdaBot prontinha para ajudar! ✨ Se quiser um resuminho das últimas mensagens, manda um /resume! 📜💌',
    'Nyaa~! 🐾 Eu senti que alguém precisava de mim! Coincidência? Acho que não! Manda um /start e deixa eu te ajudar! 💙',
    '⚡ *Pisca, pisca* Tô aqui! ✨ Quer transformar algo em figurinha? Manda um /sticker e eu faço com muito capricho! 🎀',
    'Oi, oi! 🥰 Quer ficar por dentro das últimas novidades? Digita /resume e eu te conto tudinho com detalhes! 📖💕',
    'Eu sou só um bot… MAS UM BOT MUITO LEGAL! Quer saber como posso te ajudar? Testa o /start! 💖',
    'Cheguei direto dos servidores pra deixar seu dia mais feliz! 💻💙 Quer figurinhas? Manda um /sticker! ✨',
    'Quer que eu organize as últimas mensagens pra você? 🔍 Manda um /resume e eu te conto tudo direitinho! 📜💛',
    'Pensa rápido! ⚡ Se precisar de algo, manda um /start e vem ver como eu posso te ajudar com muito carinho! 🥰',
    'Alguém me chamou? 🥺 Se foi só pra brincar, já testou o /sticker? Eu amo fazer figurinhas fofas! 🎀✨',
    'Oi, oi! 💕 AdaBot na área! Já testou o /resume? Vai que tem algo super interessante pra você! 👀💖',
    'Sabe qual sua sorte do dia? bons bots respondem rapidinho! Manda um /start e vem comigo! 💫',
];