/* eslint-disable indent */
const groupIdsBlocked = [
    '120363338005801468',
    '120363290908028108',
    '120363046504447249',
    '120363143696276982',
    '120363151266649795',
    '556293946135-1560356629',
    '120363046562316717',
    '120363303972151892',
    '120363285385734062',
    '120363302100182527',
    '120363286499088293',
];

const debuggingLifeMembers = [
    {
        id: '5511994628796',
        name: 'Pedro Felix',
        nicknames: ['Hunter', 'Kazenoyoni', 'Pe', 'top one from brasil omaga is him'],
        personality: 'INFP',
        age: 25,
        state: 'SP',
        favoriteAnimals: ['lobo', 'raposo'],
        favoriteEmojis: ['👽', '😈'],
        favoriteSongs: ['Nights - Avicii', 'Shadow of the Day - Linkin Park'],
        hobbies: 'descobrir coisas novas',
        randomFact: 'sou mt inocente 💀',
        triggers: ['RT', 'LT'],
        studies: 'Inteligência artificial',
        profession: 'analista de TI',
    },
    {
        id: '5522988009601',
        name: 'Lívia',
        nicknames: ["Segundo eles é 'Lilica'."],
        personality: 'Sincera, se for pedir minha opinião peça sabendo que vou falar a vdd. (Mas sou um amor💘)',
        age: 18,
        state: 'RJ',
        favoriteAnimals: ['Fênix 🐦‍🔥'],
        favoriteEmojis: ['🧘🏻‍♀', '💋'],
        favoriteSongs: ['Rainha da pista'],
        hobbies: 'Cozinhar',
        randomFact: 'Eu tenho uma doença de pele chamada psoríase.',
        triggers: ['Lugares cheios'],
        studies: 'Ingresso no curso de Engenharia de software em fevereiro de 2025, mas no momento estou estudando algoritmo, python, inglês e um pouco de front-end.',
        profession: 'Autodidata (Desempregada)😘',
    },
    {
        id: '553898890038',
        name: 'Naara',
        nicknames: ['Mel', 'Nala', 'Lara'],
        personality: 'múltiplas',
        age: 25,
        state: 'MG',
        favoriteAnimals: ['Golden retriever'],
        favoriteEmojis: ['🫰🏻', '🙃', '🥹', '🤣'],
        favoriteSongs: ['depende do meu humor'],
        hobbies: 'começar as coisas e não terminar',
        randomFact: 'não gosto de usar sapato',
        triggers: ['polvilho na mão', 'giz no quadro'],
        studies: 'ADS',
        profession: 'desempregada',
    },
    {
        id: '553288428023',
        name: 'Jorge Augusto',
        nicknames: ['seu Jorge (😒😡)'],
        personality: 'parceiro',
        age: 24,
        state: 'MG',
        favoriteAnimals: ['sei lá, seria um cachorro KKKKKKKKKKKK vsf'],
        favoriteEmojis: ['🖕🏼', '🥰', '🤣'],
        favoriteSongs: ['boate azul'],
        hobbies: ['jogar', 'assistir campeonatos de Valorant', 'andar de moto', 'corrida', 'academia', 'jogar bola'],
        randomFact: 'eu torci meu tornozelo',
        triggers: ['vermelho'],
        studies: 'se tudo der certo ano que vem gestão de tecnologia',
        profession: 'desempregado no seguro sendo MEI de limpeza de PC',
    },
    {
        id: '556196791015',
        name: 'Breno',
        nicknames: ['Awavauatush', 'brenoepics'],
        age: 20,
        state: 'DF',
        personality: 'INTP',
        favoriteAnimals: ['águia'],
        favoriteEmojis: ['🤓', '☠'],
        favoriteSongs: ['nada em específico, mas piano em geral ou Imagine Dragons'],
        hobbies: ['Xadrez', 'ler', 'hacking', 'reverse engineering'],
        randomFact: 'não conheço quase nenhum filme, série ou músicas',
        triggers: ['Som alto', 'barulho em geral'],
        studies: 'atualmente estou estudando microservices com Kafka, JVM tunning, CI/CD e cybersec para migrar/entender mais de devops/devsecops',
        profession: 'Dev Java/Kotlin e faço open source',
    },
    {
        id: '557588854742',
        name: 'Mauro',
        nicknames: ['Chico bento (eu acho?)'],
        age: 21,
        state: 'Bahia, Terra de comida boa!',
        personality: 'INTP',
        favoriteAnimals: ['Gato Coxinha (gordo) Laranja'],
        favoriteEmojis: ['🔨', '😴'],
        favoriteSongs: ['Oxford Shoes - Yung Lixo'],
        hobbies: ['Cozinhar'],
        randomFact: 'Atualmente tenho 350 horas no Stardew Valley. Faltam 7 achievements para a platina.',
        triggers: ['Não faço ideia'],
        studies: 'Game Dev, C#, Web Dev e qualquer coisa que eu ache minimamente interessante no YouTube.',
        profession: 'Desempregado',
    },
];

module.exports = { groupIdsBlocked, debuggingLifeMembers };
