name: Deploy AdaBot to VPS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd bots/whatsbot/
            git pull origin main
            docker compose down
            docker compose up -d --build
